#! /bin/bash
#==============================================
# Aliases - Bash Shell
#==============================================
alias :q="exit"
alias c="cls"
alias ch="history -c && > ~/.bash_history"
alias lc="colorls -sf"
alias ela='els -laH '
alias cp="cp -i"                          # confirm before overwriting something
alias df='df -h'                          # human-readable sizes
alias free='free -m'                      # show sizes in MB
alias rm='rm -i'
alias cd..='cd ..'
alias reswap='sudo swapoff -a && sudo swapon -a'
alias mem="watch -n 1 free -h"
alias bshrld='source ~/.bashrc'
alias ls='ls -ahXF --group-directories-first --time-style=+"%d.%m.%Y %H:%M" --color=auto'
alias lf='ls -lah1FX --group-directories-first --time-style=+"%d.%m.%Y %H:%M" --color=auto'
alias ll='ls -lahXF --group-directories-first --time-style=+"%d.%m.%Y %H:%M" --color=auto'
alias dir='dir -lah1FX --group-directories-first --time-style=+"%d.%m.%Y %H:%M" --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias psa='ps -axf -o pid,%cpu,%mem,bsdtime,user,command'
alias debug="set -o nounset; set -o xtrace"
alias openports='netstat -nape --inet'
alias ns='netstat -alnp --protocol=inet | grep -v ESPERANDO_FECHAR | cut -c-6,21-94 | tail '
alias logs="find /var/log -type f -exec file {} \; | grep 'text' | cut -d' ' -f1 | sed -e's/:$//g' | grep -v '[0-9]$' | xargs tail -f"
alias my_disks='echo "╓───── m o u n t . p o i n t s"; echo "╙────────────────────────────────────── ─ ─ "; lsblk -a; echo ""; echo "╓───── d i s k . u s a g e"; echo "╙────────────────────────────────────── ─ ─ "; df -h;'
alias toiletlist='for i in ${TOILET_FONT_PATH:=/usr/share/figlet}/*.{t,f}lf; do j=${i##*/}; echo ""; echo "╓───── "$j; echo "╙────────────────────────────────────── ─ ─ "; echo ""; toilet -d "${i%/*}" -f "$j" "${j%.*}"; done'
alias toiascii="toilet -t -f ascii9"
alias toifuture="toilet -t -f future"
alias pyg='pygmentize -f 256 -O style=monokai'
alias psname='process_name'

## shortcut  for iptables and pass it via sudo#
alias ipt='sudo /sbin/iptables'
 
# display all rules #
alias iptlist='sudo /sbin/iptables -L -n -v --line-numbers'
alias iptlistin='sudo /sbin/iptables -L INPUT -n -v --line-numbers'
alias iptlistout='sudo /sbin/iptables -L OUTPUT -n -v --line-numbers'
alias iptlistfw='sudo /sbin/iptables -L FORWARD -n -v --line-numbers'
alias firewall=iptlist

# get web server headers #
alias header='curl -I'
 
alias now='date +"%T"'
alias nowtime=now
alias nowdate='date +"%d-%m-%Y"'

# find out if remote server supports gzip / mod_deflate or not #
alias headerc='curl -I --compress'

alias ports='netstat -tulanp'

alias sha1='openssl sha1'

## this one saved by butt so many times ##
alias wget='wget -c'

#█▓▒░ dumb tmux trix
alias tsad="printf '\033k┐(T_T)┌\033\\'"
alias tshrug="printf '\033k┐(\`-\`)┌\033\\'"
alias tlol="printf '\033k┐(^0^)┌\033\\'"

# Testar conexão com ping
alias pggl='ping -c3 www.google.com.br' # Ping ao google a cada 3 segundos
alias puol='ping -c5 www.uol.com.br' # Ping ao UOL a cada 3 segundos

if [ $UID -gt 999 ]; then
    alias upd='~/bin/upd.sh'
    alias limp='~/bin/limp.sh'
    alias capitalize='~/bin/capitalize.sh'
    alias launch='~/bin/launch.sh'
    alias tolower='~/bin/tolower.sh'
    alias toupper='~/bin/toupper.sh'
fi

alias ips="ifconfig -a | perl -nle'/(\d+\.\d+\.\d+\.\d+)/ && print $1'"
alias listeners="lsof -iTCP -sTCP:LISTEN"

# View HTTP traffic
alias sniff="sudo ngrep -d 'wlp2s0' -t '^(GET|POST) ' 'tcp and port 80'"
alias httpdump="sudo tcpdump -i wlp2s0 -n -s 0 -w - | grep -a -o -E \"Host\: .*|GET \/.*\""

# One of @janmoesen’s ProTip™s
for method in GET HEAD POST PUT DELETE TRACE OPTIONS; do
    alias "$method"="lwp-request -m '$method'"
done

alias wttr="curl -4 http://wttr.in/~Curitiba"

alias noded="node --trace_osr --array_index_dehoisting  --trace_gc --trace_gc_verbose  --log_gc --prof --log_regexp"
alias nodec="node --crankshaft --trace_opt --use_osr --trace_osr  --trace_gc --log_regexp --log_gc --log_suspect --log_code"

alias java.debug.enable='export JAVA_OPTS="-agentlib:jdwp=transport=dt_socket,server=y,address=5009,suspend=y"'
alias java.debug.disable='export JAVA_OPTS=""'

alias ctags='ctags --exclude={docs,cache,tiny_mce,layout} --recurse';

# Git  
# Undo a `git push`
alias undopush="git push -f origin HEAD^:master"

alias g='git'
alias glog="git log --format='%Cgreen%h%Creset %C(yellow)%an%Creset - %s' --graph"
alias gpull='git pull'
alias gsa='git submodule add'
alias gclo='git clone'
alias gst='git status'
alias gst='git status'
alias gl='git pull'
alias gup='git fetch && git rebase'
alias gp='git push'
alias gc='git commit -v'
alias gca='git commit -v -a'
alias gco='git checkout'
alias gcm='git checkout master'
alias gb='git branch'
alias gba='git branch -a'
alias gcount='git shortlog -sn'
alias gcp='git cherry-pick'
alias glg='git log --stat --max-count=5'
alias glgg='git log --graph --max-count=5'
alias gss='git status -s'
alias ga='git add'
alias gm='git merge'
alias grh='git reset HEAD'
alias grhh='git reset HEAD --hard'


# utilizacao do disco
alias ducks='du -cks * | sort -rn | head'

# Reparar o apt-get
alias aptrepair='sudo apt-get -f install'

# Reparar o dpkg
alias dpkgrepair='sudo dpkg --configure -a'

alias local-ip="LC_ALL=C ifconfig | grep 'inet addr' | grep -v '127.0.0.1' | cut -d: -f2 | cut -d' ' -f1"

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# if user is not root, pass all commands via sudo #
if [ $UID -ne 0 ]; then
    alias reboot='sudo /sbin/reboot'
    alias poweroff='sudo /sbin/poweroff'
    alias halt='sudo /sbin/halt'
    alias shutdown='sudo /sbin/shutdown'
fi
