#! /bin/bash
#===========================================
# Completions
#===========================================
#===========================================
# Carrega source files em /etc/bash_completion.d
#===========================================
for file in /etc/bash_completion.d/*; do
    [ -r "$file" ] && source "$file"
done

#===========================================
# Carrega source files dentro de ~/.bash
#===========================================
for file in ~/.bash/completion_scripts/*; do
    [ -r "$file" ] && source "$file"
done
