#! /bin/bash
#=============================================
#Prompt do lado esquerdo
# PROMPT_COMMAND é executado logo antes do prompt PS1 ser exibido. 
# Vamos configurar o PS1 atraves da funcao bash_prompt.
#=============================================
PROMPT_COMMAND="history -a; history -r; bash_prompt"

if [[ ! $PROMPT_COMMAND =~ __rprompt ]]; then
    export PROMPT_COMMAND="__rprompt; ${PROMPT_COMMAND:-:}"
fi
