#!/usr/bin/env bash
# author:Matsuda Shinpei
# Date:March 2011
#
# Openbox Pipe Menu for audacious
# Feel free to change this script as you like.
# Probably, it's not so hard to make rhythembox or other media player control menus like this,
# as far as these media players support the CUI control commands.

COMMON_FUNCTIONS="$HOME/.config/openbox/scripts/common-pipemenu"

if [ -f "$COMMON_FUNCTIONS" ]; then
    . "${COMMON_FUNCTIONS}" 2> /dev/null
else
    echo $"Error: Failed to locate $COMMON_FUNCTIONS" >&2
    exit 1
fi

# Audacious not found in the system
function doMenuInstAudacious_en(){
    menuBegin
    menuSep "Audacious cannot be found"
    menuItem "How to install Audacious" "<![CDATA[x-www-browser https://www.audacious-media-player.org/download]]>" 'text-html'
    menuEnd
}

function doMenuInstAudacious_pt(){
    menuBegin
    menuSep "Audacious não Encontrado"
    menuItem "Como instalar o Audacious" "<![CDATA[x-www-browser https://www.audacious-media-player.org/download]]>" 'text-html'
    menuEnd
}

function doMenuInstAudacious(){
    # l10n support
    case "${LANG:-}" in
        de_* ) doMenuInstAudacious_en ;; # Deutsch
        da_* ) doMenuInstAudacious_en ;; # Danish
        es_* ) doMenuInstAudacious_en ;; # Española
        fr_* ) doMenuInstAudacious_en ;; # Français
        id_* ) doMenuInstAudacious_en ;; # Bahasa Indonesia
        it_* ) doMenuInstAudacious_en ;; # Italian
        lv_* ) doMenuInstAudacious_en ;; # Latvian
        pl_* ) doMenuInstAudacious_en ;; # Polish
        pt_* ) doMenuInstAudacious_pt ;; # Português
        ru_* ) doMenuInstAudacious_en ;; # Russian
        * ) doMenuInstAudacious_en ;; # Default to English
    esac
    return 0
}

function doMenuRun_en(){
    menuBegin
    menuItem "Run audacious" "audacious"
    menuEnd
}

function doMenuRun_pt(){
    menuBegin
    menuItem "Rodar audacious" "audacious"
    menuEnd
}

function doMenuRun(){
    ! checkfor "audacious" && doMenuInstAudacious && return 0
    # l10n support
    case "${LANG:-}" in
        de_* ) doMenuRun_en ;; # Deutsch
        da_* ) doMenuRun_en ;; # Danish
        es_* ) doMenuRun_en ;; # Española
        fr_* ) doMenuRun_en ;; # Français
        id_* ) doMenuRun_en ;; # Bahasa Indonesia
        it_* ) doMenuRun_en ;; # Italian
        lv_* ) doMenuRun_en ;; # Latvian
        pl_* ) doMenuRun_en ;; # Polish
        pt_* ) doMenuRun_pt ;; # Português
        ru_* ) doMenuRun_en ;; # Russian
        * ) doMenuRun_en ;; # Default to English
    esac
}

function doMenuControl_en(){
    local cursong=""
    local cslen=""
    local rpstatus=""
    local shfstatus=""
    local lblsong=""
    cursong=$(audtool --current-song)
    cslen=$(audtool --current-song-length)
    rpstatus=$(audtool --playlist-repeat-status | sed -e "s/\b\(.\)/\u\1/g")
    shfstatus=$(audtool --playlist-shuffle-status | sed -e "s/\b\(.\)/\u\1/g")
    
    menuBegin
    
    if [ ! -z "$cursong" ]; then
        lblsong=$(esc_enc "$cursong ($cslen)")
        menuSep "$lblsong"
    fi
    rpstatus=$(esc_enc "$rpstatus")
    shfstatus=$(esc_enc "$shfstatus")
    
    menuItem "Play" "<![CDATA[audtool --playback-play]]>" 'media-playback-start'
    menuItem "Pause" "<![CDATA[audtool --playback-pause]]>" 'media-playback-pause'
    menuItem "Stop" "<![CDATA[audtool --playback-stop]]>" 'media-playback-stop'
    menuItem "Previous" "<![CDATA[audtool --playlist-reverse]]>" 'media-skip-backward'
    menuItem "Next" "<![CDATA[audtool --playlist-advance]]>" 'media-skip-forward'
    menuItem "Repeat $rpstatus" "<![CDATA[audtool --playlist-repeat-toggle]]>" 'media-playlist-repeat'
    menuItem "Shuffle $shfstatus" "<![CDATA[audtool --playlist-shuffle-toggle]]>" 'media-playlist-shuffle'
    menuItem "Jump to file" "<![CDATA[audtool --jumptofile-show on]]>" 'gtk-jump-to-rtl'
    menuSep ""
    menuItem "Add files" "<![CDATA[audtool --filebrowser-show on --always-on-top on]]>" 'fileopen'
    menuItem "Preferences" "<![CDATA[audtool --preferences-show on]]>" 'preferences-system'
    menuItem "Quit audacious" "<![CDATA[audtool --shutdown]]>" 'application-exit'
    menuEnd
}

function doMenuControl_pt(){
    local cursong=""
    local cslen=""
    local rpstatus=""
    local shfstatus=""
    cursong=$(audtool --current-song)
    cslen=$(audtool --current-song-length)
    rpstatus=$(audtool --playlist-repeat-status)
    shfstatus=$(audtool --playlist-shuffle-status)
    
    if [ "$rpstatus" = "off" ]; then
        rpstatus="Desligado"
    else
        rpstatus="Ligado"
    fi
    
    if [ "$shfstatus" = "off" ]; then
        shfstatus="Desligado"
    else
        shfstatus="Ligado"
    fi
    
    menuBegin
    
    if [ ! -z "$cursong" ]; then
        lblsong=$(esc_enc "$cursong ($cslen)")
        menuSep "$lblsong"
    fi
    rpstatus=$(esc_enc "$rpstatus")
    shfstatus=$(esc_enc "$shfstatus")
    
    menuItem "Reproduzir" "<![CDATA[audtool --playback-play]]>" 'media-playback-start'
    menuItem "Pausar" "<![CDATA[audtool --playback-pause]]>" 'media-playback-pause'
    menuItem "Parar" "<![CDATA[audtool --playback-stop]]>" 'media-playback-stop'
    menuItem "Anterior" "<![CDATA[audtool --playlist-reverse]]>" 'media-skip-backward'
    menuItem "Proxima" "<![CDATA[audtool --playlist-advance]]>" 'media-skip-forward'
    menuItem "Alterna Repetir ($rpstatus)" "<![CDATA[audtool --playlist-repeat-toggle]]>" 'media-playlist-repeat'
    menuItem "Alterna Embaralhar ($shfstatus)" "<![CDATA[audtool --playlist-shuffle-toggle]]>" 'media-playlist-shuffle'
    menuItem "Ir para..." "<![CDATA[audtool --jumptofile-show on]]>" 'gtk-jump-to-rtl'
    menuSep ""
    menuItem "Abrir Arquivo(s)" "<![CDATA[audtool --filebrowser-show on --always-on-top on]]>" 'fileopen'
    menuItem "Configurações" "<![CDATA[audtool --preferences-show on]]>" 'preferences-system'
    menuItem "Sair" "<![CDATA[audtool --shutdown]]>" 'application-exit'
    menuEnd
}

function doMenuControl() {
    # l10n support
    case "${LANG:-}" in
        de_* ) doMenuControl_en ;; # Deutsch
        da_* ) doMenuControl_en ;; # Danish
        es_* ) doMenuControl_en ;; # Española
        fr_* ) doMenuControl_en ;; # Français
        id_* ) doMenuControl_en ;; # Bahasa Indonesia
        it_* ) doMenuControl_en ;; # Italian
        lv_* ) doMenuControl_en ;; # Latvian
        pl_* ) doMenuControl_en ;; # Polish
        pt_* ) doMenuControl_pt ;; # Português
        ru_* ) doMenuControl_en ;; # Russian
        * ) doMenuControl_en ;; # Default to English
    esac
}

function main(){
    [ ! "$(pidof audacious)" ] && doMenuRun && exit 0
    doMenuControl
}

main "$@"
