#!/bin/bash
# help-pipemenu
# Adapted from a script by damo <damo@bunsenlabs.org> 

COMMON_FUNCTIONS="$HOME/.config/openbox/scripts/pipe-common.sh"

if [ -f "$COMMON_FUNCTIONS" ]; then
    . "${COMMON_FUNCTIONS}" 2> /dev/null
else
    echo $"Error: Failed to locate $COMMON_FUNCTIONS" >&2
    exit 1
fi

function main(){
	local iPath=$(iconPath)
	menuBegin
	menuItem 'Indice Local' "x-www-browser \"file:///$HOME//bin/help/index.html\"" "$iPath/scalable/mimetypes/text-html.svg"
	menuItem 'ArchWiki Openbox Guide' 'x-www-browser "http://wiki.archlinux.org/index.php/Openbox"' "$iPath/scalable/mimetypes/text-html.svg"
	menuItem 'Debian Wiki Openbox Guide' 'x-www-browser "https://wiki.debian.org/Openbox"' "$iPath/scalable/mimetypes/text-html.svg"
	menuItem 'Openbox Lxlinux' 'x-www-browser "http://lxlinux.com"' "$iPath/scalable/mimetypes/text-html.svg"
	menuItem 'Openbox Homepage' 'x-www-browser "http://openbox.org/"' "$iPath/scalable/mimetypes/text-html.svg"
	menuItem 'Openbox Rc.xml-PCMag' 'x-www-browser "http://pclosmag.com/html/Issues/201107/page08.html"' "$iPath/scalable/mimetypes/text-html.svg"
	menuItem 'Urukramas Openbox Guide' 'x-www-browser "https://urukrama.wordpress.com/openbox-faq/"' "$iPath/scalable/mimetypes/text-html.svg"
	menuEnd
}

main

# menuSep 'Debian'
# menuItem 'Debian Documentation' 'x-www-browser "https://www.debian.org/doc/"'
# menuItem 'Forum' 'x-www-browser "http://forums.debian.net/"'
# menuItem 'Package Search' 'x-www-browser "https://www.debian.org/distrib/packages"'
# menuItem 'Packages Sid' 'x-www-browser "https://packages.debian.org/sid/allpackages"'
# menuItem 'Packages Testing' 'x-www-browser "https://packages.debian.org/testing/allpackages"'
# menuItem 'Package Tracker' 'x-www-browser "https://tracker.debian.org/"'
# menuItem 'Security Tracker' 'x-www-browser "https://security-tracker.debian.org/tracker/"'
# menuItem 'Wiki' 'x-www-browser "https://wiki.debian.org/"'

# menuSep 'Util'
# menuItem 'Arch Wiki' 'x-www-browser "https://wiki.archlinux.org/index.php/Table_of_contents"'
# menuItem 'Classical Stations' 'x-www-browser "http://classicalwebcast.com/"'
# menuItem 'Crontab' 'x-www-browser "http://code.tutsplus.com/tutorials/scheduling-tasks-with-cron-jobs--net-8800"'
# menuItem 'E2fsprogs' 'x-www-browser "https://en.wikipedia.org/wiki/E2fsprogs"'
# menuItem 'Internet Tools' 'x-www-browser "http://www.infobyip.com/internettools.php"'
# menuItem 'Xwd Screenshot' 'x-www-browser "http://blog.tordeu.com/?p=135"'
# menuSep

# subMenuBegin 'ConkyWWW' 'Conky'
# menuItem 'Conky Configuration Settings' 'x-www-browser "http://conky.sourceforge.net/config_settings.html"'
# menuItem 'Conky Variables' 'x-www-browser "http://conky.sourceforge.net/variables.html"'
# menuItem 'Conky man pages' 'x-terminal-emulator -T "Conky man page" -e man conky'
# subMenuEnd

# subMenuBegin 'FbpanelWWW' 'Fbpanel'
# menuItem 'Fbpanel About' 'x-www-browser "http://fbpanel.sourceforge.net/index.html"'
# menuItem 'Fbpanel-Lxlinux' 'x-www-browser "http://lxlinux.com/fbpanel.html"'
# menuItem 'Fbpanel man page' 'x-terminal-emulator -T "fbpanel man page" -e man fbpanel'
# subMenuEnd

# menuSep 'Openbox'
# subMenuBegin 'OpenboxWWW' 'Openbox'
# subMenuEnd

# menuSep 'Pcmanfm'
# menuItem 'Archlinux Pcmanfm Guide' 'x-www-browser "https://wiki.archlinux.org/index.php/PCManFM"'
# menuItem 'Lxde Pcmanfm Guide' 'x-www-browser "https://wiki.lxde.org/en/PCManFM"'

# menuSep 'Theme'
# menuItem 'Box-Look.org' 'x-www-browser "http://www.box-look.org"'
# menuItem 'Gnome-look.org' 'x-www-browser "http://gnome-look.org/"'

