#!/usr/bin/env bash
# -pipemenu

COMMON_FUNCTIONS="$HOME/.config/openbox/scripts/pipe-common.sh"

if [ -f "$COMMON_FUNCTIONS" ]; then
    . "${COMMON_FUNCTIONS}" 2> /dev/null
else
    echo $"Error: Failed to locate $COMMON_FUNCTIONS" >&2
    exit 1
fi

function doMenu() {
    # l10n support
    case "${LANG:-}" in
        de_* ) doMenu_en ;; # Deutsch
        da_* ) doMenu_en ;; # Danish
        es_* ) doMenu_en ;; # Española
        fr_* ) doMenu_en ;; # Français
        id_* ) doMenu_en ;; # Bahasa Indonesia
        it_* ) doMenu_en ;; # Italian
        lv_* ) doMenu_en ;; # Latvian
        pl_* ) doMenu_en ;; # Polish
        pt_* ) doMenu_pt ;; # Português
        ru_* ) doMenu_en ;; # Russian
        * ) doMenu_en ;; # Default to English
    esac
}

function doMenu_en() {
    menuBegin
    menuSep 
    menuItem "Audio" "$HOME/.config/openbox/scripts/inxi-pipemenu Audio" "gnome-volume-control"
    menuItem "Battery" "$HOME/.config/openbox/scripts/inxi-pipemenu Battery" "dialog-information-symbolic"
    menuItem "CPU" "$HOME/.config/openbox/scripts/inxi-pipemenu CPU" "cpuinfo"
    menuItem "Drives Info" "$HOME/.config/openbox/scripts/inxi-pipemenu DrivesGI" "drive-harddisk"
    menuItem "Drives UUID Used" "$HOME/.config/openbox/scripts/inxi-pipemenu DrivesUU" "drive-harddisk"
    menuItem "Drives Unmounted" "$HOME/.config/openbox/scripts/inxi-pipemenu DrivesUN" "drive-harddisk"
    menuItem "Graphics" "$HOME/.config/openbox/scripts/inxi-pipemenu Graphics" "mate-preferences-desktop-display"
    menuItem "Host Info" "$HOME/.config/openbox/scripts/inxi-pipemenu HostKBD" "computer"
    menuItem "Machine Info" "$HOME/.config/openbox/scripts/inxi-pipemenu MachineInfo" "computer"
    menuItem "Network" "$HOME/.config/openbox/scripts/inxi-pipemenu Network" "preferences-system-network"
    menuItem "Processes" "$HOME/.config/openbox/scripts/inxi-pipemenu Processes" "utilities-system-monitor"
    menuItem "Process Summary" "$HOME/.config/openbox/scripts/inxi-pipemenu ProcUptimeMemory" "dialog-information-symbolic"
    menuItem "Repositories" "$HOME/.config/openbox/scripts/inxi-pipemenu Repositories" "system-software-install"
    menuItem "Resolution" "$HOME/.config/openbox/scripts/inxi-pipemenu Resolution" "mate-preferences-desktop-display"
    menuItem "Temperature" "$HOME/.config/openbox/scripts/inxi-pipemenu Temperature" "hwinfo"
    menuItem "Weather" "$HOME/.config/openbox/scripts/inxi-pipemenu Weather" "weather-overcast-symbolic"
    menuEnd
}

function doMenu_pt() {
    menuBegin
    menuSep 
    menuItem "Audio" "$HOME/.config/openbox/scripts/inxi-pipemenu Audio" "gnome-volume-control"
    menuItem "Bateria" "$HOME/.config/openbox/scripts/inxi-pipemenu Battery" "dialog-information-symbolic"
    menuItem "CPU" "$HOME/.config/openbox/scripts/inxi-pipemenu CPU" "cpuinfo"
    menuItem "Discos Info" "$HOME/.config/openbox/scripts/inxi-pipemenu DrivesGI" "drive-harddisk"
    menuItem "Uso UUID" "$HOME/.config/openbox/scripts/inxi-pipemenu DrivesUU" "drive-harddisk"
    menuItem "Não Montado" "$HOME/.config/openbox/scripts/inxi-pipemenu DrivesUN" "drive-harddisk"
    menuItem "Graficos" "$HOME/.config/openbox/scripts/inxi-pipemenu Graphics" "mate-preferences-desktop-display"
    menuItem "Host" "$HOME/.config/openbox/scripts/inxi-pipemenu HostKBD" "computer"
    menuItem "Máquina" "$HOME/.config/openbox/scripts/inxi-pipemenu MachineInfo" "computer"
    menuItem "Rede" "$HOME/.config/openbox/scripts/inxi-pipemenu Network" "preferences-system-network"
    menuItem "Processos" "$HOME/.config/openbox/scripts/inxi-pipemenu Processes" "utilities-system-monitor"
    menuItem "Sumario" "$HOME/.config/openbox/scripts/inxi-pipemenu ProcUptimeMemory" "dialog-information-symbolic"
    menuItem "Repositórios" "$HOME/.config/openbox/scripts/inxi-pipemenu Repositories" "system-software-install"
    menuItem "Resolução" "$HOME/.config/openbox/scripts/inxi-pipemenu Resolution" "mate-preferences-desktop-display"
    menuItem "Temperatura" "$HOME/.config/openbox/scripts/inxi-pipemenu Temperature" "hwinfo"
    menuItem "Clima" "$HOME/.config/openbox/scripts/inxi-pipemenu Weather" "weather-overcast-symbolic"
    menuEnd
}

function doAudio() {
    inxi -A -c0 | zenity  --text-info --title "Inxi information..." --width 900 --height 300 --font "Hack Nerd Font Mono 9" 2> /dev/null
    return 0
}

function doBattery() {
    inxi -B -c0 | zenity  --text-info --title "Inxi information..." --width 900 --height 300 --font "Hack Nerd Font Mono 9" 2> /dev/null
    return 0
}

function doCPU() {
    inxi -C -c0 | zenity  --text-info --title "Inxi information..." --width 900 --height 300 --font "Hack Nerd Font Mono 9" 2> /dev/null
    return 0
}

function doDrivesGI() {
    inxi -d -c0 | zenity  --text-info --title "Inxi information..." --width 900 --height 300 --font "Hack Nerd Font Mono 9" 2> /dev/null
    return 0
}

function doDrivesUU() {
    inxi -plu -c0 | zenity  --text-info --title "Inxi information..." --width 900 --height 300 --font "Hack Nerd Font Mono 9" 2> /dev/null
    return 0
}

function doDrivesUN() {
    inxi -o -c0 | zenity  --text-info --title "Inxi information..." --width 900 --height 300 --font "Hack Nerd Font Mono 9" 2> /dev/null
    return 0
}

function doGraphics() {
    inxi -G -c0 | zenity  --text-info --title "Inxi information..." --width 900 --height 300 --font "Hack Nerd Font Mono 9" 2> /dev/null
    return 0
}

function doHostKBD() {
    inxi -S -c0 | zenity  --text-info --title "Inxi information..." --width 900 --height 300 --font "Hack Nerd Font Mono 9" 2> /dev/null
    return 0
}

function doMachine() {
    inxi -MZ -c0 | zenity  --text-info --title "Inxi information..." --width 900 --height 300 --font "Hack Nerd Font Mono 9" 2> /dev/null
    return 0 
}

function doNetwork() {
    inxi -NnixxxZ -c0 | zenity  --text-info --title "Inxi information..." --width 900 --height 300 --font "Hack Nerd Font Mono 9" 2> /dev/null
    return 0
}

function doProcesses() {
    inxi -t cm -x -c0 | zenity  --text-info --title "Inxi information..." --width 900 --height 300 --font "Hack Nerd Font Mono 9" 2> /dev/null
    return 0
}

function doProcUptimeMemory() {
    inxi -I -c0 | zenity  --text-info --title "Inxi information..." --width 900 --height 300 --font "Hack Nerd Font Mono 9" 2> /dev/null
    return 0
}

function doRepositories() {
    inxi -r -c0 | zenity  --text-info --title "Inxi information..." --width 900 --height 300 --font "Hack Nerd Font Mono 9" 2> /dev/null
    return 0
}

function doResolution() {
    inxi -G -c0 | zenity  --text-info --title "Inxi information..." --width 900 --height 300 --font "Hack Nerd Font Mono 9" 2> /dev/null
    return 0
}

function doTemperature() {
    inxi -s -c0 | zenity  --text-info --title "Inxi information..." --width 900 --height 300 --font "Hack Nerd Font Mono 9" 2> /dev/null
    return 0
}

function doWeather() {
    #inxi -xxx -W 55051 -c0 | zenity  --text-info --title "Inxi information..." --width 900 --height 300 --font "Hack Nerd Font Mono 9"
    inxi -xxx -W curitiba,brazil -c0 | zenity  --text-info --title "Inxi information..." --width 900 --height 300 --font "Hack Nerd Font Mono 9" 2> /dev/null
    return 0
}

function doAll() {
    inxi -Fxxxz -c0 | zenity  --text-info --title "Inxi information..." --width 900 --height 300 --font "Hack Nerd Font Mono 9" 2> /dev/null
    return 0
}

function main() {
    local cmd=${1:-menu}
    case "$cmd" in
        All)
            doAll
            ;;
        Audio)
            doAudio
            ;;
        Battery)
            doBattery
            ;;
        CPU)
            doCPU
            ;;
        DrivesGI)
            doDrivesGI
            ;;
        DrivesUU)
            doDrivesUU
            ;;
        DrivesUN)
            doDrivesUN
            ;;
        Graphics)
            doGraphics
            ;;
        HostKBD)
            doHostKBD
            ;;
        MachineInfo)
            doMachine Info
            ;;
        Network)
            doNetwork
            ;;
        Processes)
            doProcesses
            ;;
        ProcUptimeMemory)
            doProcUptimeMemory
            ;;
        Repositories)
            doRepositories
            ;;
        Resolution)
            doResolution
            ;;
        Temperature)
            doTemperature
            ;;
        Weather)
            doWeather
            ;;
        *)
            doMenu
    esac
}

main "$1"

