#!/usr/bin/env bash
# -pipemenu

COMMON_FUNCTIONS="$HOME/.config/openbox/scripts/pipe-common.sh"

if [ -f "$COMMON_FUNCTIONS" ]; then
    . "${COMMON_FUNCTIONS}" 2> /dev/null
else
    echo $"Error: Failed to locate $COMMON_FUNCTIONS" >&2
    exit 1
fi

function doMenu() {
    # l10n support
    case "${LANG:-}" in
        de_* ) doMenu_en ;; # Deutsch
        da_* ) doMenu_en ;; # Danish
        es_* ) doMenu_en ;; # Española
        fr_* ) doMenu_en ;; # Français
        id_* ) doMenu_en ;; # Bahasa Indonesia
        it_* ) doMenu_en ;; # Italian
        lv_* ) doMenu_en ;; # Latvian
        pl_* ) doMenu_en ;; # Polish
        pt_* ) doMenu_pt ;; # Português
        ru_* ) doMenu_en ;; # Russian
        * ) doMenu_en ;; # Default to English
    esac
}

function doMenu_en() {
    menuBegin
    menuSep 
    menuItem 'Audio' '~/.config/openbox/scripts/inxi-pipemenu Audio' 'gnome-volume-control'
    #menuItem 'Battery' '~/.config/openbox/scripts/inxi-pipemenu Battery' 'dialog-information-symbolic'
    menuItem 'CPU' '~/.config/openbox/scripts/inxi-pipemenu CPU' 'cpuinfo'
    menuItem 'Drives Info' '~/.config/openbox/scripts/inxi-pipemenu DrivesGI' 'drive-harddisk'
    menuItem 'Drives UUID Used' '~/.config/openbox/scripts/inxi-pipemenu DrivesUU' 'drive-harddisk'
    menuItem 'Drives Unmounted' '~/.config/openbox/scripts/inxi-pipemenu DrivesUN' 'drive-harddisk'
    menuItem 'Graphics' '~/.config/openbox/scripts/inxi-pipemenu Graphics' 'mate-preferences-desktop-display'
    menuItem 'Host Info' '~/.config/openbox/scripts/inxi-pipemenu HostKBD' 'computer'
    menuItem 'Machine Info' '~/.config/openbox/scripts/inxi-pipemenu MachineInfo' 'computer'
    menuItem 'Network' '~/.config/openbox/scripts/inxi-pipemenu Network' 'preferences-system-network'
    menuItem 'Processes' '~/.config/openbox/scripts/inxi-pipemenu Processes' 'utilities-system-monitor'
    menuItem 'Process Summary' '~/.config/openbox/scripts/inxi-pipemenu ProcUptimeMemory' 'dialog-information-symbolic'
    menuItem 'Repositories' '~/.config/openbox/scripts/inxi-pipemenu Repositories' 'system-software-install'
    menuItem 'Resolution' '~/.config/openbox/scripts/inxi-pipemenu Resolution' 'mate-preferences-desktop-display'
    menuItem 'Temperature' '~/.config/openbox/scripts/inxi-pipemenu Temperature' 'hwinfo'
    menuItem 'Weather' '~/.config/openbox/scripts/inxi-pipemenu Weather' 'weather-overcast-symbolic'
    menuEnd
}

function doMenu_pt() {
    menuBegin
    menuSep 
    menuItem 'Audio' '~/.config/openbox/scripts/inxi-pipemenu Audio' 'gnome-volume-control'
    #menuItem 'Battery' '~/.config/openbox/scripts/inxi-pipemenu Battery' 'dialog-information-symbolic'
    menuItem 'CPU' '~/.config/openbox/scripts/inxi-pipemenu CPU' 'cpuinfo'
    menuItem 'Discos Info' '~/.config/openbox/scripts/inxi-pipemenu DrivesGI' 'drive-harddisk'
    menuItem 'Uso UUID' '~/.config/openbox/scripts/inxi-pipemenu DrivesUU' 'drive-harddisk'
    menuItem 'Não Montado' '~/.config/openbox/scripts/inxi-pipemenu DrivesUN' 'drive-harddisk'
    menuItem 'Graficos' '~/.config/openbox/scripts/inxi-pipemenu Graphics' 'mate-preferences-desktop-display'
    menuItem 'Host' '~/.config/openbox/scripts/inxi-pipemenu HostKBD' 'computer'
    menuItem 'Máquina' '~/.config/openbox/scripts/inxi-pipemenu MachineInfo' 'computer'
    menuItem 'Rede' '~/.config/openbox/scripts/inxi-pipemenu Network' 'preferences-system-network'
    menuItem 'Processos' '~/.config/openbox/scripts/inxi-pipemenu Processes' 'utilities-system-monitor'
    menuItem 'Sumario' '~/.config/openbox/scripts/inxi-pipemenu ProcUptimeMemory' 'dialog-information-symbolic'
    menuItem 'Repositórios' '~/.config/openbox/scripts/inxi-pipemenu Repositories' 'system-software-install'
    menuItem 'Resolução' '~/.config/openbox/scripts/inxi-pipemenu Resolution' 'mate-preferences-desktop-display'
    menuItem 'Temperatura' '~/.config/openbox/scripts/inxi-pipemenu Temperature' 'hwinfo'
    menuItem 'Clima' '~/.config/openbox/scripts/inxi-pipemenu Weather' 'weather-overcast-symbolic'
    menuEnd
}

function doAudio() {
    inxi -A -c0 | zenity  --text-info --title "Inxi information..." --width 600 --height 300 --font "Hack Nerd Font Mono 9"
    return 0
}

function doBattery() {
    inxi -B -c0 | zenity  --text-info --title "Inxi information..." --width 600 --height 300 --font "Hack Nerd Font Mono 9"
    return 0
}

function doCPU() {
    inxi -C -c0 | zenity  --text-info --title "Inxi information..." --width 600 --height 300 --font "Hack Nerd Font Mono 9"
    return 0
}

function doDrivesGI() {
    inxi -d -c0 | zenity  --text-info --title "Inxi information..." --width 600 --height 300 --font "Hack Nerd Font Mono 9"
    return 0
}

function doDrivesUU() {
    inxi -plu -c0 | zenity  --text-info --title "Inxi information..." --width 600 --height 300 --font "Hack Nerd Font Mono 9"
    return 0
}

function doDrivesUN() {
    inxi -o -c0 | zenity  --text-info --title "Inxi information..." --width 600 --height 300 --font "Hack Nerd Font Mono 9"
    return 0
}

function doGraphics() {
    inxi -G -c0 | zenity  --text-info --title "Inxi information..." --width 600 --height 300 --font "Hack Nerd Font Mono 9"
    return 0
}

function doHostKBD() {
    inxi -S -c0 | zenity  --text-info --title "Inxi information..." --width 600 --height 300 --font "Hack Nerd Font Mono 9"
    return 0
}

function doMachine() {
    inxi -M -c0 | zenity  --text-info --title "Inxi information..." --width 600 --height 300 --font "Hack Nerd Font Mono 9"
    return 0 
}

function doNetwork() {
    inxi -i -c0 | zenity  --text-info --title "Inxi information..." --width 600 --height 300 --font "Hack Nerd Font Mono 9"
    return 0
}

function doProcesses() {
    inxi -t cm -x -c0 | zenity  --text-info --title "Inxi information..." --width 600 --height 300 --font "Hack Nerd Font Mono 9"
    return 0
}

function doProcUptimeMemory() {
    inxi -I -c0 | zenity  --text-info --title "Inxi information..." --width 600 --height 300 --font "Hack Nerd Font Mono 9"
    return 0
}

function doRepositories() {
    inxi -r -c0 | zenity  --text-info --title "Inxi information..." --width 600 --height 300 --font "Hack Nerd Font Mono 9"
    return 0
}

function doResolution() {
    inxi -G -c0 | zenity  --text-info --title "Inxi information..." --width 600 --height 300 --font "Hack Nerd Font Mono 9"
    return 0
}

function doTemperature() {
    inxi -s -c0 | zenity  --text-info --title "Inxi information..." --width 600 --height 300 --font "Hack Nerd Font Mono 9"
    return 0
}

function doWeather() {
    #inxi -xxx -W 55051 -c0 | zenity  --text-info --title "Inxi information..." --width 600 --height 300 --font "Hack Nerd Font Mono 9"
    inxi -xxx -W curitiba,brazil -c0 | zenity  --text-info --title "Inxi information..." --width 600 --height 300 --font "Hack Nerd Font Mono 9"
    return 0
}

function doAll() {
    inxi -Fxxxz -c0 | zenity  --text-info --title "Inxi information..." --width 600 --height 300 --font "Hack Nerd Font Mono 9"
    return 0
}

function main() {
    local cmd=${1:-menu}
    case "$cmd" in
        All)
            doAll
            ;;
        Audio)
            doAudio
            ;;
        Battery)
            doBattery
            ;;
        CPU)
            doCPU
            ;;
        DrivesGI)
            doDrivesGI
            ;;
        DrivesUU)
            doDrivesUU
            ;;
        DrivesUN)
            doDrivesUN
            ;;
        Graphics)
            doGraphics
            ;;
        HostKBD)
            doHostKBD
            ;;
        MachineInfo)
            doMachine Info
            ;;
        Network)
            doNetwork
            ;;
        Processes)
            doProcesses
            ;;
        ProcUptimeMemory)
            doProcUptimeMemory
            ;;
        Repositories)
            doRepositories
            ;;
        Resolution)
            doResolution
            ;;
        Temperature)
            doTemperature
            ;;
        Weather)
            doWeather
            ;;
        *)
            doMenu
    esac
}

main $1

