#!/usr/bin/env bash
# -pipemenu

COMMON_FUNCTIONS="$HOME/.config/openbox/scripts/common-pipemenu"

if [ -f "$COMMON_FUNCTIONS" ]; then
    . "${COMMON_FUNCTIONS}" 2> /dev/null
else
    echo $"Error: Failed to locate $COMMON_FUNCTIONS" >&2
    exit 1
fi

# Inxi not found in the system
function doMenuInstInxi_en(){
    menuBegin
    menuSep "Inxi cannot be found"
    menuItem "How to install Inxi" "<![CDATA[x-www-browser https://www.ostechnix.com/how-to-find-your-system-details-using-inxi/]]>" 'text-html'
    menuEnd
}

function doMenuInstInxi_pt(){
    menuBegin
    menuSep "Inxi não Encontrado"
    menuItem "Como instalar o Inxi" "<![CDATA[x-www-browser https://www.ostechnix.com/how-to-find-your-system-details-using-inxi/]]>" 'text-html'
    menuEnd
}

function doMenuInstInxi() {
    # l10n support
    case "${LANG:-}" in
        de_* ) doMenuInstInxi_en ;; # Deutsch
        da_* ) doMenuInstInxi_en ;; # Danish
        es_* ) doMenuInstInxi_en ;; # Española
        fr_* ) doMenuInstInxi_en ;; # Français
        id_* ) doMenuInstInxi_en ;; # Bahasa Indonesia
        it_* ) doMenuInstInxi_en ;; # Italian
        lv_* ) doMenuInstInxi_en ;; # Latvian
        pl_* ) doMenuInstInxi_en ;; # Polish
        pt_* ) doMenuInstInxi_pt ;; # Português
        ru_* ) doMenuInstInxi_en ;; # Russian
        * ) doMenuInstInxi_en ;; # Default to English
    esac
    return 0
}

function doMenu_en(){
    menuBegin
    menuSep
    menuItem "Audio" "<![CDATA[$HOME/.config/openbox/scripts/inxi-pipemenu Audio]]>" "gnome-volume-control"
    menuItem "Battery" "<![CDATA[$HOME/.config/openbox/scripts/inxi-pipemenu Battery]]>" "dialog-information-symbolic"
    menuItem "CPU" "<![CDATA[$HOME/.config/openbox/scripts/inxi-pipemenu CPU]]>" "cpu"
    menuItem "Drives Info" "<![CDATA[$HOME/.config/openbox/scripts/inxi-pipemenu DrivesGI]]>" "drive-harddisk"
    menuItem "Drives UUID Used" "<![CDATA[$HOME/.config/openbox/scripts/inxi-pipemenu DrivesUU]]>" "drive-harddisk"
    menuItem "Drives Unmounted" "<![CDATA[$HOME/.config/openbox/scripts/inxi-pipemenu DrivesUN]]>" "drive-harddisk"
    menuItem "Graphics" "<![CDATA[$HOME/.config/openbox/scripts/inxi-pipemenu Graphics]]>" "mate-preferences-desktop-display"
    menuItem "Host Info" "<![CDATA[$HOME/.config/openbox/scripts/inxi-pipemenu HostKBD]]>" "computer"
    menuItem "Machine Info" "<![CDATA[$HOME/.config/openbox/scripts/inxi-pipemenu MachineInfo]]>" "computer"
    menuItem "Network" "<![CDATA[$HOME/.config/openbox/scripts/inxi-pipemenu Network]]>" "preferences-system-network"
    menuItem "Processes" "<![CDATA[$HOME/.config/openbox/scripts/inxi-pipemenu Processes]]>" "utilities-system-monitor"
    menuItem "Process Summary" "<![CDATA[$HOME/.config/openbox/scripts/inxi-pipemenu ProcUptimeMemory]]>" "dialog-information-symbolic"
    menuItem "Repositories" "<![CDATA[$HOME/.config/openbox/scripts/inxi-pipemenu Repositories]]>" "system-software-install"
    menuItem "Resolution" "<![CDATA[$HOME/.config/openbox/scripts/inxi-pipemenu Resolution]]>" "mate-preferences-desktop-display"
    menuItem "Temperature" "<![CDATA[$HOME/.config/openbox/scripts/inxi-pipemenu Temperature]]>" "hwinfo"
    menuItem "Weather" "<![CDATA[$HOME/.config/openbox/scripts/inxi-pipemenu Weather]]>" "weather-overcast-symbolic"
    menuEnd
}

function doMenu_pt() {
    menuBegin
    menuSep
    menuItem "$(esc_enc Audio)" "<![CDATA[$HOME/.config/openbox/scripts/inxi-pipemenu Audio]]>" "gnome-volume-control"
    menuItem "$(esc_enc Bateria)" "<![CDATA[$HOME/.config/openbox/scripts/inxi-pipemenu Battery]]>" "dialog-information-symbolic"
    menuItem "$(esc_enc CPU)" "<![CDATA[$HOME/.config/openbox/scripts/inxi-pipemenu CPU]]>" "cpu"
    menuItem "$(esc_enc Discos Info)" "<![CDATA[$HOME/.config/openbox/scripts/inxi-pipemenu DrivesGI]]>" "drive-harddisk"
    menuItem "$(esc_enc Uso UUID)" "<![CDATA[$HOME/.config/openbox/scripts/inxi-pipemenu DrivesUU]]>" "drive-harddisk"
    menuItem "$(esc_enc Não Montado)" "<![CDATA[$HOME/.config/openbox/scripts/inxi-pipemenu DrivesUN]]>" "drive-harddisk"
    menuItem "$(esc_enc Gráficos)" "<![CDATA[$HOME/.config/openbox/scripts/inxi-pipemenu Graphics]]>" "mate-preferences-desktop-display"
    menuItem "$(esc_enc Host)" "<![CDATA[$HOME/.config/openbox/scripts/inxi-pipemenu HostKBD]]>" "computer"
    menuItem "$(esc_enc Máquina)" "<![CDATA[$HOME/.config/openbox/scripts/inxi-pipemenu MachineInfo]]>" "computer"
    menuItem "$(esc_enc Rede)" "<![CDATA[$HOME/.config/openbox/scripts/inxi-pipemenu Network]]>" "preferences-system-network"
    menuItem "$(esc_enc Processos)" "<![CDATA[$HOME/.config/openbox/scripts/inxi-pipemenu Processes]]>" "utilities-system-monitor"
    menuItem "$(esc_enc Sumário)" "<![CDATA[$HOME/.config/openbox/scripts/inxi-pipemenu ProcUptimeMemory]]>" "dialog-information-symbolic"
    menuItem "$(esc_enc Repositórios)" "<![CDATA[$HOME/.config/openbox/scripts/inxi-pipemenu Repositories]]>" "system-software-install"
    menuItem "$(esc_enc Resolução)" "<![CDATA[$HOME/.config/openbox/scripts/inxi-pipemenu Resolution]]>" "mate-preferences-desktop-display"
    menuItem "$(esc_enc Temperatura)" "<![CDATA[$HOME/.config/openbox/scripts/inxi-pipemenu Temperature]]>" "hwinfo"
    menuItem "$(esc_enc Clima)" "<![CDATA[$HOME/.config/openbox/scripts/inxi-pipemenu Weather]]>" "weather-overcast-symbolic"
    menuEnd
}

function doMenu() {
    ! checkfor "inxi" && doMenuInstInxi && return 0
    # l10n support
    case "${LANG:-}" in
        de_* ) doMenu_en ;; # Deutsch
        da_* ) doMenu_en ;; # Danish
        es_* ) doMenu_en ;; # Española
        fr_* ) doMenu_en ;; # Français
        id_* ) doMenu_en ;; # Bahasa Indonesia
        it_* ) doMenu_en ;; # Italian
        lv_* ) doMenu_en ;; # Latvian
        pl_* ) doMenu_en ;; # Polish
        pt_* ) doMenu_pt ;; # Português
        ru_* ) doMenu_en ;; # Russian
        * ) doMenu_en ;; # Default to English
    esac
    return 0
}

function doAudio() {
    eval "inxi -A -c0 | $@"
    return 0
}

function doBattery() {
    eval "inxi -B -c0 | $@"
    return 0
}

function doCPU() {
    eval "inxi -C -c0 | $@"
    return 0
}

function doDrivesGI() {
    eval "inxi -d -c0 | $@"
    return 0
}

function doDrivesUU() {
    eval "inxi -plu -c0 | $@"
    return 0
}

function doDrivesUN() {
    eval "inxi -o -c0 | $@"
    return 0
}

function doGraphics() {
    eval "inxi -G -c0 | $@"
    return 0
}

function doHostKBD() {
    eval "inxi -S -c0 | $@"
    return 0
}

function doMachine() {
    eval "inxi -MZ -c0 | $@"
    return 0
}

function doNetwork() {
    eval "inxi -NnixxxZ -c0 | $@"
    return 0
}

function doProcesses() {
    eval "inxi -t cm -x -c0 | $@"
    return 0
}

function doProcUptimeMemory() {
    eval "inxi -I -c0 | $@"
    return 0
}

function doRepositories() {
    eval "inxi -r -c0 | $@"
    return 0
}

function doResolution() {
    eval "inxi -G -c0 | $@"
    return 0
}

function doTemperature() {
    eval "inxi -s -c0 | $@"
    return 0
}

function doWeather() {
    #inxi -xxx -W 55051 -c0 | ....
    eval "inxi -xxx -W curitiba,brazil -c0 | $@"
    return 0
}

function doAll() {
    eval "inxi -Fxxxz -c0 | $@"
    return 0
}

function main() {
    local cmd=${1:-menu}
    if checkfor "gxmessage"; then
        local o="gxmessage -font \"Hack Nerd Font Mono 9\" -center -file - 2> /dev/null"
    elif checkfor "zenity"; then
        local o="zenity  --text-info --title \"Inxi information...\" --width 900 --height 300 --font \"Hack Nerd Font Mono 9\" 2> /dev/null"
    else
        local o="cat -"
    fi
    case "$cmd" in
        All)
            doAll $o
        ;;
        Audio)
            doAudio $o
        ;;
        Battery)
            doBattery $o
        ;;
        CPU)
            doCPU $o
        ;;
        DrivesGI)
            doDrivesGI $o
        ;;
        DrivesUU)
            doDrivesUU $o
        ;;
        DrivesUN)
            doDrivesUN $o
        ;;
        Graphics)
            doGraphics $o
        ;;
        HostKBD)
            doHostKBD $o
        ;;
        MachineInfo)
            doMachine $o
        ;;
        Network)
            doNetwork $o
        ;;
        Processes)
            doProcesses $o
        ;;
        ProcUptimeMemory)
            doProcUptimeMemory $o
        ;;
        Repositories)
            doRepositories $o
        ;;
        Resolution)
            doResolution $o
        ;;
        Temperature)
            doTemperature $o
        ;;
        Weather)
            doWeather $o
        ;;
        *)
            doMenu
    esac
}

main "$@"

