#!/usr/bin/env bash
COMMON_FUNCTIONS="$HOME/.config/openbox/scripts/pipe-common.sh"

if [ -f "$COMMON_FUNCTIONS" ]; then
    . "${COMMON_FUNCTIONS}" 2> /dev/null
else
    echo $"Error: Failed to locate $COMMON_FUNCTIONS" >&2
    exit 1
fi

function doMenu() {
    # l10n support
    case "${LANG:-}" in
        de_* ) doMenu_en ;; # Deutsch
        da_* ) doMenu_en ;; # Danish
        es_* ) doMenu_en ;; # Española
        fr_* ) doMenu_en ;; # Français
        id_* ) doMenu_en ;; # Bahasa Indonesia
        it_* ) doMenu_en ;; # Italian
        lv_* ) doMenu_en ;; # Latvian
        pl_* ) doMenu_en ;; # Polish
        pt_* ) doMenu_pt ;; # Português
        ru_* ) doMenu_en ;; # Russian
        * ) doMenu_en ;; # Default to English
    esac
}

function doMenu_en() {
    local f=""
    local fpath=""
    menuBegin

    grep "file:///" ~/.local/share/recently-used.xbel | cut -d "\"" -f 2 | tac | while read line; do
        f=$(echo "$line" | sed 's,.*/,,' | sed 'y/+/ /; s/%/\\x/g')
        f=$(echo -en "$f")
        fpath=$(echo "$line" | sed 's/file:\/\///g' | sed 'y/+/ /; s/%/\\x/g')
        fpath=$(echo -en "$fpath")
        [ -e "$fpath" ] && menuItem "$f" "xdg-open \"$line\""
    done;
    
    menuSep 
    menuItem "Clear Recent Documents" "rm ~/.local/share/recently-used.xbel"
    menuEnd
}

function doMenu_pt() {
    local f=""
    menuBegin
    
    #grep "file:///" ~/.local/share/recently-used.xbel | tail -n15 | cut -d "\"" -f 2 | tac | while read line; do
    #    f=$(echo "$line" | sed 's,.*/,,' | sed 'y/+/ /; s/%/\\x/g')
    #    f=$(echo -en "$f")
    #    menuItem "$f" "xdg-open \"$line\""
    #done;

    grep "file:///" ~/.local/share/recently-used.xbel | cut -d "\"" -f 2 | tac | while read line; do
        f=$(echo "$line" | sed 's,.*/,,' | sed 'y/+/ /; s/%/\\x/g')
        f=$(echo -en "$f")
        fpath=$(echo "$line" | sed 's/file:\/\///g' | sed 'y/+/ /; s/%/\\x/g')
        fpath=$(echo -en "$fpath")
        [ -e "$fpath" ] && menuItem "$f" "xdg-open \"$line\""
    done;
    
    menuSep 
    menuItem "Limpar lista" "rm ~/.local/share/recently-used.xbel"
    menuEnd
}

doMenu

