#! /bin/bash
#==============================================
# Exports (auto generated. Do not edit) - Bash Shell
#==============================================
function do_exports() {
export -f lman
export -f do_xarg
export -f is_empty
export -f is_not_empty
export -f is_file
export -f is_dir
export -f rpass
export -f sys_load
export -f aencrypt
export -f bencrypt
export -f decrypt
export -f ncpu
export -f my_ps
export -f psgrep
export -f sub
export -f goto
export -f cpf
export -f mvf
export -f mkf
export -f cmd_exists
export -f top_cmds
export -f lsr
export -f cls
export -f decode_64
export -f encode_64
export -f dwordnet
export -f dacron
export -f djargon
export -f dfoldoc
export -f dthesaurus
export -f hora
export -f dataiso
export -f data
export -f yday
export -f tday
export -f bro-grep
export -f bro-zgrep
export -f jsgrep
export -f cssgrep
export -f phpgrep
export -f htmgrep
export -f wdevgrep
export -f topcount
export -f mostcolor
export -f my_distro
export -f uptime_since
export -f free_mem
export -f total_mem
export -f avail_mem
export -f ff
export -f fff
export -f fd
export -f fdf
export -f fe
export -f jobs_count
export -f stoppedjobs
export -f laptop_battery
export -f mouse_battery
export -f up
export -f bak
export -f space
export -f core
export -f graph
export -f ethcard
export -f wfcard
export -f fawk
export -f black
export -f red
export -f green
export -f yellow
export -f blue
export -f magenta
export -f cyan
export -f white
export -f onblack
export -f onred
export -f ongreen
export -f onyellow
export -f onblue
export -f onmagenta
export -f oncyan
export -f onwhite
export -f cblk
export -f cred
export -f cgre
export -f cyel
export -f cblu
export -f cmag
export -f ccya
export -f cwhi
export -f cm_fu_motd
export -f calc
export -f digga
export -f tre
export -f prepend-path
export -f duplines
export -f uniqlines
export -f hostname2ip
export -f e_header
export -f e_arrow
export -f e_success
export -f e_error
export -f e_warning
export -f e_underline
export -f e_bold
export -f e_note
export -f e_itemok
export -f e_itemnok
export -f e_itemarrow
export -f echo_fail
export -f echo_pass
export -f authme
export -f manopt
export -f couch-get
export -f couch-put
export -f couch-post
export -f couch-delete
export -f awksub
export -f decimal2hex
export -f rsync_bpk
export -f editexec
export -f _dir_count
export -f _file_count
export -f _pwd_size
export -f gitdone
export -f do_magic
export -f ArrayElemDisplay
export -f GetLastElem
export -f qh
export -f qtxt
export -f _mkdir
export -f position_cursor
export -f display_status
export -f is_installed
export -f ip_inf
export -f xfind
export -f is_newer
export -f is_systype
export -f is_alpha
export -f is_int
export -f is_float
export -f cache
export -f serve_py
export -f serve_php
export -f ask_confirmation
export -f is_confirmed
export -f get_full_path
export -f exesudo
export -f servername_pull
export -f servername_push
export -f c_loadandgo
export -f ask_pw
export -f ask_usr
export -f run_psudo
export -f selcryptfile
export -f encryptfile
export -f decryptfile
export -f get_xserver
export -f set_display
export -f exists_fileordir
export -f is_active
export -f activate
export -f deactivate
export -f t
export -f psproc
export -f psonly
export -f gen_lock
export -f eexit
export -f interface_info
export -f dtranslate
export -f mostused
export -f cd
export -f md_view
export -f phrase
export -f json_py
export -f MIT
export -f at_line_no
export -f meteo
export -f escape
export -f shorten
export -f matches
export -f fstr
export -f mkgit
export -f argc
export -f edit
export -f screens_count
export -f du_full
export -f du_short
export -f hosts_up
export -f screens_and_jobs_count
export -f strLen
export -f strLenC
export -f strU8DiffLen
export -f process_name
export -f cl
export -f do_extract
export -f qt_mail
export -f tem_mail
export -f uptime_active
export -f random_cow_file
export -f you_have_mail
export -f my_motd
export -f draw
export -f color_bar
export -f greetings
}

do_exports
